mrkdwn/mrkdwn/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mrkdwn.views.home', name='home'),
    # url(r'^mrkdwn/', include('mrkdwn.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^notes/', include('notepad.urls', namespace='notes')),
    url(r'^admin/', include(admin.site.urls)),
)

mrkdwn/notepad/urls.py
from django.conf.urls import patterns, url

from notepad import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^new/$', views.new, name='new'),
    url(r'^create/$', views.create, name='create'),
    url(r'^(?P<note_id>\d+)/$', views.detail, name='detail'),
    url(r'^(?P<note_id>\d+)/edit/$', views.edit, name='edit'),
    url(r'^(?P<note_id>\d+)/update/$', views.update, name='update'),
)

pollster/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pollster.views.home', name='home'),
    # url(r'^pollster/', include('pollster.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

mrkdwn/notepad/models.py
from django.db import models

class Note(models.Model):
  title        = models.CharField(max_length=100)
  published_at = models.DateTimeField('date published')
  content      = models.TextField()

  def __unicode__(self):
    return self.title

mrkdwn/notepad/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
import datetime

from notepad.models import Note

def index(request):
    note_list = Note.objects.all()
    return render(request, 'notes/index.html', {'note_list': note_list })

def detail(request, note_id):
    note = get_object_or_404(Note, pk=note_id)
    return render(request, 'notes/detail.html', {'note': note})

def new(request):
    return render(request, 'notes/new.html')

def create(request):
    note = Note(title=request.POST['title'],
                content=request.POST['content'],
                published_at=str(datetime.date.today()))
    note.save()
    return HttpResponseRedirect(reverse('notes:index'))

def edit(request, note_id):
    note = get_object_or_404(Note, pk=note_id)
    return render(request, 'notes/edit.html', {'note': note})

def update(request, note_id):
    note = get_object_or_404(Note, pk=note_id)

    note.title   = request.POST['title']
    note.content = request.POST['content']
    note.save()

    return HttpResponseRedirect(reverse('notes:index'))

mrkdwn/notepad/templates/notes/detail.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'notes/style.css' %}" />
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="{% static 'notes/javascripts/showdown.js' %}"></script>
<script src="{% static 'notes/javascripts/markdown.js' %}"></script>

<div class="p4">
  <h1 class="h1">{{ note.title }}</h1>
  <div class="h3 mid-gray mt4 mb4" id="md" data-md="{{ note.content }}"></div>

  <a href="{% url 'notes:edit' note.id %}" class="button button-big button-blue">Edit</a>
  <a href="{% url 'notes:index' %}" class="button button-big button-gray">See All</a>
</div>

mrkdwn/notepad/templates/notes/edit.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'notes/style.css' %}" />

<div class="p1">
  <form action="{% url 'notes:update' note.id %}" method="post" class="form form-light form-inline">
    {% csrf_token %}
    <input type="submit" value="Update" class="button button-blue mb1" />
    <input type="text" name="title" value="{{ note.title }}" class="input" />
    <a href="{% url 'notes:detail' note.id %}" class="button right button-gray">Back</a>
    <input type="hidden" name="content" value="{{ note.content }}" class="input" id="md-content" data-md="{{ note.content }}" />
    <div id="editor"></div>
  </form>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script src="{% static 'notes/javascripts/r.js' %}"></script>
<script src="{% static 'notes/javascripts/ace.js' %}"></script>
<script src="{% static 'notes/javascripts/editor.js' %}"></script>

mrkdwn/notepad/templates/notes/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'notes/style.css' %}" />

<div class="p4">
  <h1 class="h1">Notes</h1>
  {% if note_list %}
    <div class='mb4 mt4'>
      {% for note in note_list %}
        <a href="{% url 'notes:detail' note.id %}">
          <div class="oh mb1 clearfix">
            <div class="oh bg-light-gray p1">
              <p>
                <span class="h3">{{ note.title }}</span> <br>
                <span class="mid-gray">{{ note.published_at }}</span>
              </p>
            </div>
          </div>
        </a>
      {% endfor %}
    </div>
  {% else %}
    <p>You don't have any notes.</p>
  {% endif %}

  <a href="{% url 'notes:new' %}" class="button button-big button-blue">New Note</a>
</div>

mrkdwn/notepad/templates/notes/new.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'notes/style.css' %}" />

<div class="p4">
  <h1 class="h1">Create a new note.</h1>

  <form action="{% url 'notes:create' %}" method="post" class="form form-light form-stacked">
    {% csrf_token %}
    <label for="title">Title</label>
    <input type="text" name="title" value="{{ note.title }}" class="input"/>
    <label for="content">Content</label>
    <input type="text" name="content" value="{{ note.content }}" class="input"/>
    <input type="submit" value="Create New Note" class="button button-big button-blue" />
    <a href="{% url 'notes:index' %}" class="button button-big button-gray">Back</a>
  </form>
</div>